### PR TITLE
Update ru_ru.lang

### PR DESCRIPTION
**Pull request by AndrionisPrime**
Updated ru_ru.lang to mod v.24.1.3.

### CODE REVIEW

**Comment by AndrionisPrime** [comment]
This translation has been significantly updated and now corresponds to the current English translation.
The wording of the new translation more clearly reflects the intention of the English translation.
Some successful formulations of the old translation have been retained.

**Comment by thexaero** [comment]
Thank you very much!
I'll take a look when I have time.

**Comment by thexaero** [comment]
Hey, do you want to look over your translations and fix conflicts now that I merged an older PR?

**Comment by AndrionisPrime** [comment]
Hi. Okay, I'll update the translation.

**Pull request closed without merging**
